//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiIdeaService.MonitoreoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Monitoreo", Namespace="http://schemas.datacontract.org/2004/07/NiIdeaService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Monitoreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidad_co2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidad_no2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidad_so2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigo_ctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigo_mField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigo_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_iniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad_co2 {
            get {
                return this.cantidad_co2Field;
            }
            set {
                if ((this.cantidad_co2Field.Equals(value) != true)) {
                    this.cantidad_co2Field = value;
                    this.RaisePropertyChanged("cantidad_co2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad_no2 {
            get {
                return this.cantidad_no2Field;
            }
            set {
                if ((this.cantidad_no2Field.Equals(value) != true)) {
                    this.cantidad_no2Field = value;
                    this.RaisePropertyChanged("cantidad_no2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad_so2 {
            get {
                return this.cantidad_so2Field;
            }
            set {
                if ((this.cantidad_so2Field.Equals(value) != true)) {
                    this.cantidad_so2Field = value;
                    this.RaisePropertyChanged("cantidad_so2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo_ct {
            get {
                return this.codigo_ctField;
            }
            set {
                if ((this.codigo_ctField.Equals(value) != true)) {
                    this.codigo_ctField = value;
                    this.RaisePropertyChanged("codigo_ct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo_m {
            get {
                return this.codigo_mField;
            }
            set {
                if ((this.codigo_mField.Equals(value) != true)) {
                    this.codigo_mField = value;
                    this.RaisePropertyChanged("codigo_m");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo_p {
            get {
                return this.codigo_pField;
            }
            set {
                if ((this.codigo_pField.Equals(value) != true)) {
                    this.codigo_pField = value;
                    this.RaisePropertyChanged("codigo_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                if ((this.fecha_finField.Equals(value) != true)) {
                    this.fecha_finField = value;
                    this.RaisePropertyChanged("fecha_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ini {
            get {
                return this.fecha_iniField;
            }
            set {
                if ((this.fecha_iniField.Equals(value) != true)) {
                    this.fecha_iniField = value;
                    this.RaisePropertyChanged("fecha_ini");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitoreoWS.IMonitoreoService")]
    public interface IMonitoreoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/CreaMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/CreaMonitoreoResponse")]
        NiIdeaService.MonitoreoWS.Monitoreo CreaMonitoreo(System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/CreaMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/CreaMonitoreoResponse")]
        System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> CreaMonitoreoAsync(System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ObtieneMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ObtieneMonitoreoResponse")]
        NiIdeaService.MonitoreoWS.Monitoreo ObtieneMonitoreo(int codigo_m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ObtieneMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ObtieneMonitoreoResponse")]
        System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> ObtieneMonitoreoAsync(int codigo_m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ModificaMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ModificaMonitoreoResponse")]
        NiIdeaService.MonitoreoWS.Monitoreo ModificaMonitoreo(int codigo_m, System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ModificaMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ModificaMonitoreoResponse")]
        System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> ModificaMonitoreoAsync(int codigo_m, System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/EliminarMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/EliminarMonitoreoResponse")]
        void EliminarMonitoreo(int codigo_m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/EliminarMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/EliminarMonitoreoResponse")]
        System.Threading.Tasks.Task EliminarMonitoreoAsync(int codigo_m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ListarMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ListarMonitoreoResponse")]
        NiIdeaService.MonitoreoWS.Monitoreo[] ListarMonitoreo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoreoService/ListarMonitoreo", ReplyAction="http://tempuri.org/IMonitoreoService/ListarMonitoreoResponse")]
        System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo[]> ListarMonitoreoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoreoServiceChannel : NiIdeaService.MonitoreoWS.IMonitoreoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoreoServiceClient : System.ServiceModel.ClientBase<NiIdeaService.MonitoreoWS.IMonitoreoService>, NiIdeaService.MonitoreoWS.IMonitoreoService {
        
        public MonitoreoServiceClient() {
        }
        
        public MonitoreoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoreoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoreoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoreoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NiIdeaService.MonitoreoWS.Monitoreo CreaMonitoreo(System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p) {
            return base.Channel.CreaMonitoreo(fecha_ini, fecha_fin, cantidad_so2, cantidad_no2, cantidad_co2, codigo_ct, codigo_p);
        }
        
        public System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> CreaMonitoreoAsync(System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p) {
            return base.Channel.CreaMonitoreoAsync(fecha_ini, fecha_fin, cantidad_so2, cantidad_no2, cantidad_co2, codigo_ct, codigo_p);
        }
        
        public NiIdeaService.MonitoreoWS.Monitoreo ObtieneMonitoreo(int codigo_m) {
            return base.Channel.ObtieneMonitoreo(codigo_m);
        }
        
        public System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> ObtieneMonitoreoAsync(int codigo_m) {
            return base.Channel.ObtieneMonitoreoAsync(codigo_m);
        }
        
        public NiIdeaService.MonitoreoWS.Monitoreo ModificaMonitoreo(int codigo_m, System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p) {
            return base.Channel.ModificaMonitoreo(codigo_m, fecha_ini, fecha_fin, cantidad_so2, cantidad_no2, cantidad_co2, codigo_ct, codigo_p);
        }
        
        public System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo> ModificaMonitoreoAsync(int codigo_m, System.DateTime fecha_ini, System.DateTime fecha_fin, int cantidad_so2, int cantidad_no2, int cantidad_co2, int codigo_ct, int codigo_p) {
            return base.Channel.ModificaMonitoreoAsync(codigo_m, fecha_ini, fecha_fin, cantidad_so2, cantidad_no2, cantidad_co2, codigo_ct, codigo_p);
        }
        
        public void EliminarMonitoreo(int codigo_m) {
            base.Channel.EliminarMonitoreo(codigo_m);
        }
        
        public System.Threading.Tasks.Task EliminarMonitoreoAsync(int codigo_m) {
            return base.Channel.EliminarMonitoreoAsync(codigo_m);
        }
        
        public NiIdeaService.MonitoreoWS.Monitoreo[] ListarMonitoreo() {
            return base.Channel.ListarMonitoreo();
        }
        
        public System.Threading.Tasks.Task<NiIdeaService.MonitoreoWS.Monitoreo[]> ListarMonitoreoAsync() {
            return base.Channel.ListarMonitoreoAsync();
        }
    }
}
